```mermaid
graph LR
    n0["configurator"]
    n1["model"]
    n2["train"]
    n3["bench"]
    n4["sample"]
    n5["config.eval_gpt2"]
    n6["config.eval_gpt2_xl"]
    n7["config.train_shakespeare_char"]
    n8["config.eval_gpt2_large"]
    n9["config.finetune_shakespeare"]
    n2 --> n1
    n3 --> n1
    n4 --> n1
```